# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: install
description: install node and dependencies

inputs:
  node-version:
    description: node version to install
    required: false
    default: '18'

runs:
  using: 'composite'
  steps:
    - name: install node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: install dependencies
      shell: bash
      run: npm ci
