# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: houseplant / check

on:
  workflow_call:
    inputs:
      node-version:
        description: node version to install
        required: false
        type: string
      node-environment:
        description: node environment to use
        required: false
        type: string
      flags:
        description: flags to pass to the command
        required: false
        type: string

jobs:
  format:
    name: ☑️
    uses: cassiecascade/houseplant/.github/workflows/run.yml@main
    with:
      command: check:format ${{ inputs.flags }}
      node-version: ${{ inputs.node-version }}
      node-environment: ${{ inputs.node-environment }}

  lint:
    name: ☑️
    uses: cassiecascade/houseplant/.github/workflows/run.yml@main
    with:
      command: check:lint ${{ inputs.flags }}
      node-version: ${{ inputs.node-version }}
      node-environment: ${{ inputs.node-environment }}
